on:
  push:
    tags:
      - case1/*
jobs:
  deploy:
    name: deploy to xxx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Modify version info
        run: sed -i "s#version:\w*#version:${{ github.sha }}#" version.yaml

      - name: Commit report
        run: |
          git config --local user.name 'GA Robot'
          git config --local user.email '<>'
          git add .
          git commit -m "🤖 Release New Version"
          git push
